import type { MonsterMaster } from './types.js';

export const MONSTERS: MonsterMaster[] = [
  // Front monsters
  {
    id: 'iron-golem',
    name: 'アイアンゴーレム',
    role: 'front',
    hp: 28,
    power: 3,
    category: '防御',
    canRevive: false,
    description: '強固な防御力を持つ鉄の巨人。',
  },
  {
    id: 'berserk',
    name: 'ベルセルク',
    role: 'front',
    hp: 15,
    power: 5,
    category: '攻撃',
    canRevive: false,
    counterDef: { name: '激昂カウンター', type: 'self' },
    description: '戦いの中で力を増す狂戦士。',
  },
  {
    id: 'vampire-lord',
    name: 'ヴァンパイアロード',
    role: 'front',
    hp: 18,
    power: 4,
    category: '攻撃',
    canRevive: false,
    counterDef: { name: '吸血カウンター', type: 'self' },
    description: '敵の血を吸って強くなる吸血鬼の王。',
  },
  {
    id: 'mirror-knight',
    name: 'ミラーナイト',
    role: 'front',
    hp: 20,
    power: 4,
    category: '防御',
    canRevive: false,
    description: '攻撃を跳ね返す鏡の騎士。',
  },
  {
    id: 'death-knight',
    name: 'デスナイト',
    role: 'front',
    hp: 16,
    power: 6,
    category: '特殊',
    canRevive: false,
    counterDef: { name: '業炎カウンター', type: 'self' },
    description: '自らのHPを代償に強力な攻撃を放つ死の騎士。',
  },
  {
    id: 'skeleton-lancer',
    name: 'スケルトンランサー',
    role: 'front',
    hp: 19,
    power: 4,
    category: '攻撃',
    canRevive: false,
    description: '槍で前衛と後衛を同時に貫く骸骨の槍兵。',
  },
  {
    id: 'phoenix-warrior',
    name: 'フェニックスウォリアー',
    role: 'front',
    hp: 16,
    power: 4,
    category: '特殊',
    canRevive: true,
    counterDef: { name: '炎鳥カウンター', type: 'self' },
    description: '死から蘇る不死鳥の戦士。',
  },
  {
    id: 'storm-warlock',
    name: 'ストームウォーロック',
    role: 'front',
    hp: 17,
    power: 5,
    category: '特殊',
    canRevive: false,
    counterDef: { name: '嵐カウンター', type: 'self' },
    description: '嵐を操る強力な魔法使い。',
  },
  {
    id: 'guard-beast',
    name: 'ガードビースト',
    role: 'front',
    hp: 25,
    power: 3,
    category: '防御',
    canRevive: false,
    description: '仲間を守るために戦う守護獣。',
  },
  {
    id: 'chain-soldier',
    name: 'チェインソルジャー',
    role: 'front',
    hp: 18,
    power: 3,
    category: '特殊',
    canRevive: false,
    counterDef: { name: '連鎖カウンター', type: 'self' },
    description: '連続攻撃で力を蓄える連鎖の兵士。',
  },
  // Rear monsters
  {
    id: 'holy-priest',
    name: 'ホーリープリースト',
    role: 'rear',
    hp: 12,
    power: 1,
    category: '回復',
    canRevive: false,
    description: '回復と蘇生を行う聖なる司祭。',
  },
  {
    id: 'shadow-witch',
    name: 'シャドウウィッチ',
    role: 'rear',
    hp: 9,
    power: 5,
    category: '攻撃',
    canRevive: false,
    description: '敵の後衛を直接狙う影の魔女。',
  },
  {
    id: 'curse-shaman',
    name: 'カースシャーマン',
    role: 'rear',
    hp: 10,
    power: 2,
    category: '妨害',
    canRevive: false,
    counterDef: { name: '呪いカウンター', type: 'apply' },
    description: '敵に呪いをかけて弱らせる呪術師。',
  },
  {
    id: 'war-bird',
    name: 'ウォーバード',
    role: 'rear',
    hp: 12,
    power: 2,
    category: '補助',
    canRevive: false,
    description: '仲間のカウンターを増やす戦闘鳥。',
  },
  {
    id: 'necromancer',
    name: 'ネクロマンサー',
    role: 'rear',
    hp: 11,
    power: 2,
    category: '補助',
    canRevive: false,
    counterDef: { name: '死霊カウンター', type: 'self' },
    description: '死者を蘇らせる死霊術師。',
  },
  {
    id: 'poison-doctor',
    name: 'ポイズンドクター',
    role: 'rear',
    hp: 10,
    power: 2,
    category: '妨害',
    canRevive: false,
    counterDef: { name: '毒カウンター', type: 'apply' },
    description: '毒で敵を蝕む毒医師。',
  },
  {
    id: 'echo-mage',
    name: 'エコーメイジ',
    role: 'rear',
    hp: 8,
    power: 3,
    category: '特殊',
    canRevive: false,
    description: '仲間の力を増幅させる反響魔術師。',
  },
  {
    id: 'storm-shaman',
    name: 'ストームシャーマン',
    role: 'rear',
    hp: 9,
    power: 2,
    category: '攻撃',
    canRevive: false,
    counterDef: { name: '烈風カウンター', type: 'apply' },
    description: '嵐の力で敵を苦しめる嵐の巫女。',
  },
  {
    id: 'barrier-maiden',
    name: 'バリアメイデン',
    role: 'rear',
    hp: 16,
    power: 2,
    category: '回復',
    canRevive: false,
    description: '仲間を守る障壁を張る乙女。',
  },
  {
    id: 'yell-dancer',
    name: 'エールダンサー',
    role: 'rear',
    hp: 11,
    power: 2,
    category: '補助',
    canRevive: false,
    counterDef: { name: '応援カウンター', type: 'threshold', threshold: 3 },
    description: '応援で仲間を鼓舞するダンサー。',
  },
];

export const FRONT_MONSTERS = MONSTERS.filter((m) => m.role === 'front');
export const REAR_MONSTERS = MONSTERS.filter((m) => m.role === 'rear');

export function getMonsterById(id: string): MonsterMaster | undefined {
  return MONSTERS.find((m) => m.id === id);
}
